---
title: Личный блог Макаровой Н.Н.
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: makarnat73@mail.ru
lang: ru-RU
description: Описание этого сайта, которое редактируется в файле _config.yml. Его
  следует подправить позже.
copyright: "© 2018 Личный блог Макаровой Н.Н."
baseurl: ''
url: http://makarnat73.github.io/
github_username: makarnat73
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-remote-theme
remote_theme: mmistakes/jekyll-theme-basically-basic
